# -*- coding: utf-8 -*-
"""fifa_analise_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12M0JG98KHTlgMuDnhp_rr-OFMackCVl_
"""

#Importando a biblioteca pandas
import pandas as pd

#Importando os dados
dados= pd.read_csv('fifa.csv')

#Primeira visualização dos dados
dados

#Visualizando as 5 primeiras linhas
dados.head()

#Visualizando as últimas 5 linhas
dados.tail()

#Visaulizando as colunas
dados.columns

#Visualizando o index
dados.index

#Visualizando apenas os dados Name, Nationality e Wage
dados[['Name','Nationality','Wage']]

#Selecionando o index 0 a 4
dados.iloc[0:4]

#Visualizando os dados do index 2,2
dados.iloc[2,2]

#Visualizando apenas os dados dos jogadores brasileiros
dados.loc[dados["Nationality"]=='Brazil']

#Visualizando os dados Weight usando o sort_values
dados.sort_values('Weight')

#Adiconando a tabela total, que é a soma da tabela Acceleration, Agillity e Reactions
dados["Total"]=dados['Acceleration'] + dados['Agility'] + dados['Reactions']
dados

#Criando a variavel dados_total que contém os dados Name e Total

dados_total=dados[['Name', 'Total']]

dados_total.sort_values("Total", ascending=False)

#Criando um arquivo csv com os dados obtidos
dados_total.to_csv("dados_total.csv", index=False)

#Lendo os dados
dados_total=pd.read_csv('dados_total.csv')
dados_total

